### ISSUE TITLE
Effective rates in Market Filter

### ISSUE THREAD

**Issue by TheAmigo** [mainIine/foe-helfer-extension#1601]
Some people post offers that are several ages behind.  When the ratio of goods is 2:1, they get sorted to the top even though they are not good offers.  To keep such clutter out of the view, I suggest adding a checkbox that will instead show the effective rate.

Effective rate = (OfferQty/NeedQty) / power(2, NeedAge - OfferAge)

As an example, here's someone offering 60 Salt for 30 Coke.  With a ratio of 2, it sorts to the top.  Using the formula above, the effective rate is:

Ratio = OfferQty/NeedQty = 60/30 = 2
NeedAge = 7 (IA)
OfferAge = 4 (HMA)
AgeFactor = power(2, 7-4) = 2^3 = 8
Effective rate = Ratio / AgeFactor = 2/8 = .25

![image](https://user-images.githubusercontent.com/4148739/93003556-551fa400-f505-11ea-9251-e421ec2c10cf.png)

Note that the same formula works for trading up ages as well as down.  The offers of 50 Salt for 100 Gold are divided by 2^(-1) because Gold is one age less than Salt.  Thus the effective rate is 1 even though the ratio is .5

**Comment by andrgin** [comment]
1.) The filter option "disadvantage" does exactly this. If you remove the checkbox it will remove all the trades that are over 2 eras.

2.) While trading goods of the next era 2:1 is very common for low level players this will get far off from reality the further you get up. I am making 1500 SAAB goods per day and most sold goods are himeji (VZ) and arc (future). Even trading far lower than 1:2 would be a win.

3.) The tool was designed to only filter trades, but not change sort order. The reason is that it will make it a lot easier to find the trades in the ingame trade window if both have the same sorting order.
