### ISSUE TITLE
Negotiation hiccups

### ISSUE THREAD

**Issue by DJKC123** [mainIine/foe-helfer-extension#1615]
The negotiation helper for the most part is very helpful but I go through streaks that I have to pay a bunch of 10 diamonds for another turn.  That probably is going to happen so not a problem.  I'm sure FoE knows your strategy of a 1st turn so they mix things up.

What I do notice is when there are two big rows of choices that many times the negotiation helper doesn't ever select all of the items, even to the very end which leaves a big problem such as shown on this screen shot:   http://prntscr.com/usjjsp

It had selected only two of the five bottom row items over all the selections:  http://prntscr.com/usjvqu

Going into the last guess I had a 7% chance and it still didn't select three of the items for the first time.

There is a logic problem as there was a 0% chance that it would succeed.  

Great program - love it - wish FoE would let you bring back some of the features you had to take out but it is still  very helpful!!

Thanks!

**Comment by andrgin** [comment]
There is no specific strategy in the negotiation helper except the first round that is hardcoded as "use 5 different goods" as everything else would not make sense.
The rest is calculated by brute force. We have simulated all possible combinations and stored the best strategy for each green/yellow/red combination in tables that are shipped with the extension.

The gotiation helper always picks the guess with  highest chance of solving.
If there are multiple guesses with equal chance it picks the guess with lowest average goods costs while the goods costs are weighted by the priority you can choose with drag/drop before the first round.

So if the negotiation helper decided to not pick 7 different goods in the first 3 rounds it is either because the chance of solving is higher or more likely because it has determined that chance is equal, but good costs are lower because it saves the rare goods.

**Comment by Th3C0D3R** [comment]
Maybe try to use the tavern boost to get a fourth turn so making this negotiation with only three turns is very hard
