### ISSUE TITLE
suggestion: menu bar on top

### ISSUE THREAD

**Issue by HAL09001** [mainIine/foe-helfer-extension#1719]
Option to place on large resolution the menu on top.
Maybe similar to this
![image](https://user-images.githubusercontent.com/48470058/102690046-12a3ec80-4203-11eb-9687-2020c98dcdf5.png)

**Comment by outoftheline** [comment]
Hmm, I don't know what to think about this. 
Our intention ist not to overlap any game functionality permanently.
How much space is there normally for you?

**Comment by andrgin** [comment]
Overlapping ingame menus is a very bad idea. Also on big screens there is plenty of space on the right or bottom and on smaller screens there is no space at the top.

**Comment by HAL09001** [comment]
This wouldn't overlay any information in the game on my screen, the space is blank. This means, it overlaps less screen than the normal menu.

![image](https://user-images.githubusercontent.com/48470058/102697438-0d13ca00-4236-11eb-9a78-4c2185ffcd2c.png)

**Comment by belikoviv** [comment]
> Hmm, I don't know what to think about this.
> Our intention ist not to overlap any game functionality permanently.
> How much space is there normally for you?

I think that it is player choice - to overlap or not native game elements.
So I think that this variant also may be released (as variant).
But this is varian for VERY wide screens :)
I have resolution 2133x1090 and my Helper you may see on screen:
![2012211249](https://user-images.githubusercontent.com/35531243/102769526-71946d80-438b-11eb-9c7c-676af45c3673.png)

**Comment by andrgin** [comment]
1.) Yes with the box it is possible

2.) We want to avoid overlapping ingame displays as players sometimes report that to Inno and we do not want to waste support resources as this would backfire soon.

**Comment by belikoviv** [comment]
With the box it is possible to move menu into any place on screen.
But box has to minuses:
1. It has own title on window which increase window height.
2. It collapse only from bottom to top so I have no reason to place it near bottom of screen because after collapsing it has slightly stupid position:
![2012220919](https://user-images.githubusercontent.com/35531243/102860956-7b73aa80-4437-11eb-81c2-7555d4adcbe3.png)
![2012220920](https://user-images.githubusercontent.com/35531243/102860961-7ca4d780-4437-11eb-9d36-623032c9f469.png)
It will be great if box has possibility to expand from bottom to top so I can place it like this:
![2012220922](https://user-images.githubusercontent.com/35531243/102861075-b37aed80-4437-11eb-81d2-5166e81a7983.png)

**Comment by HAL09001** [comment]
Maybe removing the title and moving the expand/collapse butten to the side would benefit both of our wishes.
I could move the bar to the top and you could move the bar to the bottom.
![image](https://user-images.githubusercontent.com/48470058/102882647-fa281200-444e-11eb-8d3b-3cb6271ed99a.png)
![image](https://user-images.githubusercontent.com/48470058/102882665-001df300-444f-11eb-8ab9-a423d0cc3d26.png)

**Comment by belikoviv** [comment]
> Maybe removing the title and moving the expand/collapse butten to the side would benefit both of our wishes.

Title visibilty can be customizable.
The position of expand/collapse button can also be customizable.

But you forgot one important point - direction of expand/collapse. When the menu box is placed at the bottom of the screen - box must collapse from top to bottom so button (or title) must be at very bottom of screen when box collapsed.
