### ISSUE TITLE
Lavender fields, and Vineyard not calculating properly in Production overview

### ISSUE THREAD

**Issue by Omnigus** [mainIine/foe-helfer-extension#1777]
Hi 
as the title says, 
once a vineyard has been set up and the Lavender fields added, only the fp is added to the production efficiency, not the added size of the vineyard.
a lvl 3 vineyard with 6 fields suddenly produces 24 Forge Points, but still only occupies 16 spaces ... makes the efficiency 1,5 
where in fact that it produces 24 fp on a 75 spot = 0,32 efficiency. 

best regards Omnigus

**Comment by andrgin** [comment]
This is a known limitation because we only see the production of the building, not the conditions under which the production happens.
For vineyard, winter train etc. it is required to link additional buildings next to it. For set buildings like cherry garden or winter bakery you have individual buildings producing FP, but additional FP production when arranging them in a certain pattern.
In theory it would be possible to identify the whole set and combine the whole set, but we would basically would need to copy the whole ingame calculation logic which is not worth the effort especially considering all the creative cherry garden sets and it would still not be 100% accurate as some effects like happiness are not even transfered in this case, but sent to the client as a generic "adjacent buildings" boost where you have to way of identifying where this comes from.
