### ISSUE TITLE
Suggestion: LB investment for attack power

### ISSUE THREAD

**Issue by frankmorgner** [mainIine/foe-helfer-extension#1830]
FoE helper already brings an overview which great building should be leveled/built next in terms of maximizing FP income. The same calculation should be possible for maximizing attack power. The overview given [here](https://foe-maths.de/military_boost.html) could be taken as starting point.

**Comment by frankmorgner** [comment]
Duplicate of  #1825

**Comment by outoftheline** [comment]
Like you said it's a duplicate. 
I'd like to add that there are only 4 GB that directly boost your attack power. Opening the GB Calculator and comparing the FP you need to invest takes only 4 clicks. Therefore I don't really think this is necessary.

**Comment by frankmorgner** [comment]
that's not exactly true.

- First, there is also arctic orangery, which may be calculated based on some expected/average damage. The average damage per FP calculation is not trivial for most people...
- Second, simply looking at the raw FP that need to be paid, ignores the 90% conveyor chain, which are typically used.

**Comment by outoftheline** [comment]
> Second, simply looking at the raw FP that need to be paid, ignores the 90% conveyor chain, which are typically used.
That is not what I said. I mean this:
![image](https://user-images.githubusercontent.com/7482863/107771263-ceccef80-6d3a-11eb-8363-df888154905e.png) 
![image](https://user-images.githubusercontent.com/7482863/107771356-ef954500-6d3a-11eb-944d-2dca4610344c.png)

> First, there is also arctic orangery, which may be calculated based on some expected/average damage. The average damage per FP calculation is not trivial for most people...
Sure, that's why I said **directly** boost

**Comment by frankmorgner** [comment]
I've prepared an excel sheet to compare average damage per FP from AO with one of Zeus, CoA, CdM. If you're planning to implement this feature, I'm happy to share the calculation as starting point for you.

**Comment by frankmorgner** [comment]
Yes, Kraken and Virgo should be ignored for this comparison. Their fighting effects cannot be easily compared with the other fighting LBs. (In my opinion, their effects are actually worthless most of the time; I didn't build them.)

If I were you, I would avoid comparing FP vs attack bonus. Most top players don't value FP that much, because all their great buildings are at level 80+ and all research is done. There just isn't a lot of return if you need to put thousands of FP into one of those great buildings.

But sure, in terms of how much FPs you need to invest, you could easily consider the extra FP from the castell (although I still believe that Zeus is way cheaper not only because of the straight up lower cost, but also because of the opportunity costs due to its smaller size). One way to calculate this would be to take the player's average fights per GBG season, which gives [around 1,7 FP per fight on average in diamond leage, for example](https://forgeofempires.fandom.com/wiki/Guild_Battlegrounds). Then you simply assume that the fighting power is directly proportional to the number of fights per GBG, which  increases the FPs gained every two weeks.

The reality, of course is a bit more complicated... Not every GBG season is the same and you should normally consider the maximum attrition (see [this guide which compares fighting power with max. attrition](https://www.youtube.com/watch?v=_3PplYM7FcI)). But I think the estimation in the previous paragraph is good enough.

Attached to this post you find a speadsheed wich compares the fighting power given from AO with that given from Zeus. Please notify me if you need this in english. For clearity, the calculation is based on the attack value of the actual unit (steel warden). but for comparing AO vs Zeus, this value could actually be reduced to make the calculation meaningful for all ages. Note that GBG fights are typically fights against units of your age, to which the AO's effect applies.

[AO vs Zeus.xlsx](https://github.com/mainIine/foe-helfer-extension/files/6463856/AO.vs.Zeus.xlsx)

**Comment by Gindi4711** [comment]
A quick update:

I decided to implement this feature.

1.) I will use a combined approach like for goods that you can specify a tuning value how many daily FP is 1% more attack worth to you. The default value is 0.5FP per % offense boost.

The idea behind this is that in the city of an average player there are still shrines of knowledge producing 1FP per 5 tiles (4+street) or 0.2FP per tile.
I assume that you can replace those shrines of knowledge if you want to with some daily prizes that give around 0.8% attack boost per tile (I know there are ones that give 1% per tile, but this means you are missing out on some other daily prizes), so it would be 0.25FP per % attack boost for attacking armies. I assume that defense for attacking armies is worth as much as attack, so 2*0.25FP = 0.5FP per % offense boost.

For more advanced players you will be most likely be replacing your terrace farms with , so a value of 1FP per % offense boost would make more sense if your main focus is attack boost.

For endgame players that have already replaced all their FP buildings it is a bit more difficult, but I assume that FP always has some value to them. Even endgame players would not tear down their lvl80 Hagia even if it gets them 50% more attack boost for attacking armies (would equal 2.5FP per % offense boost).

2.) For AO it gets a bit more complicated:
Critical hit of AO means 50% more damage, but this does not equal to 50% more attack. This is some strange non linear scaling and strange steps in between depending on how much damage you are already doing.

Example (attack values are always the average of the zone):
With 100% attack value of the enemy defense value (400 attack, 400 defense) you are doing 4-6 (average 5) damage
With 116% attack value you are doing 4-7 (average 5.5) damage. You need 16% more attack to deal 10% more damage
With 140% attack value you are doing 5-7 (average 6) damage. You need 40% more attack for 20% more damage
With 163% attack value you are doing 6-7 (average 6.5) damage. You need 60% more attack for 30% more damage
With 195% attack value you are doing 6-8 (average 7) damage. You need 95% more attack for 40% more damage
With 260% attack value you are doing 7-8 (average 7.5) damage. You need 160% more attack for 50% more damage
Going up the ratio get worse.

In reality situation gets a little more complicated because it is more about hit to kill than actual damage points. If you are doing 5-7 or 9 damage does not really matter. It will still take 2 hits, but doing 4 vs. 5 damage means 1 hit less.

a) I will assume that on average 1% more damage will need 2% more attack value and the critical hit of +50% damage will be treated as +100% attack value. I know the real hit to kill values could vary a lot depending on the situation, but I doubt most players using this tool will be doing more advanced calculations.

b) AO will only give an attack boost while the other millitary buildings will give a defense boost for attacking armies as well. Like defined above I treat defense boost for attacking armies equal to attack boost, so I will divide the boost of the AO by 2.

So overall we are back to 50% (50% more damage = 100% more attack value = 50% more attack value + 50% more defense value).

**Comment by frankmorgner** [comment]
Maybe one should exclude AO for the initial release of this feature. 

Indeed, I've stubled across the issue of attack vs. damage as well:
https://github.com/frankmorgner/foe-battle-simulator/blob/9740caf30fff1e3550951c3ac550d0db2cf05c1c/foe_battle_simulator.py#L327-L377
The only source for the actual damage calculation I've found was https://www.youtube.com/watch?v=ksX0w1h4-4U

With my simulator I've done some match ups, which indicate that there are some hot squares, where raising the attack/defense doesn't have a lot of influence. On the other hand, AO only influences the outcome, when you're already inside those squares and 10% AO chance raises the chance for winning the fight by around 20%. With this in mind, it doesn't seem so clear how to value attack vs chance of critical hit... 

![grafik](https://user-images.githubusercontent.com/1266577/121166729-9dc87b80-c851-11eb-8ae0-6dd1e156485d.png)
Computer has 827 attack, 827 defense (attrition 63), my script performed 10 fights for a player that has 0-1600 attack/defense (both raised in 50% steps). The three images are for Chance for critical hit (AO) of 0%, 10% and 20%:

**Comment by Gindi4711** [comment]
1.) I have my values from an Excel sheet that was posted on the foe forum in 2014: https://forum.en.forgeofempires.com/index.php?threads/the-damage-calculator.25048/
Here are the values:





<meta name="ProgId" content="Excel.Sheet">
<meta name="Generator" content="Microsoft Excel 15">
<link id="Main-File" rel="Main-File" href="file:///C:/Users/andr_gin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel="File-List" href="file:///C:/Users/andr_gin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>





0-1   Damage | 0,153846154 | 0,251572327
0-2   Damage | 0,25210084 | 0,322580645
1-2   Damage | 0,323529412 | 0,344827586
1-3   Damage | 0,345323741 | 0,454545455
1-4   Damage | 0,455882353 | 0,509803922
2-4   Damage | 0,510204082 | 0,597826087
2-5   Damage | 0,6 | 0,697674419
3-5   Damage | 0,698924731 | 0,798165138
3-6   Damage | 0,8 | 0,921052632
4-6   Damage | 0,922330097 | 1,107142857
4-7   Damage | 1,111111111 | 1,210526316
5-7   Damage | 1,212121212 | 1,612903226
6-7   Damage | 1,621621622 | 1,655172414
6-8   Damage | 1,666666667 | 2,25
7-8   Damage | 2,258064516 | 2,941176471
7-9   Damage | 2,962962963 | 3,346153846
8-9   Damage | 3,392857143 | 5,833333333
9-9   Damage | 6 | 9,090909091
9-10   Damage | 9,111111111 | 18,5
Unit is   Dead | 19 | 190

The gaps between seem to be untested so far (for example 1,107 - 1.111).
I have not checked the values so far, but it seems the author has invested quite some time into it. Also they seem to roughly match the rounded values from FoeTipps.

2.) You simulation looks really interesting. I think I will have to look through that code when I have a bit more time ;-)

For the results: This is interesting as this was completely different from what I expected. I would assume that chance of winning always changes when there is a change in hit to kill. Lets take the sector attack 400-800 with defense 1000-1600 as an example. From 1000 to 1600 defense there are 3 different steps:
.) 1036-1183 gives 3-5 damage, average 3,7 hits per kill
.) 1185-1378 gives 2-5 damage, average 3,28 hits per kill
.) 1383-1620 gives 2-4 damage, average 2,94 hits per kill

For the attack value of 400-800 the same applies.
So what I would expect is to see 3x3 blocks instead of 1 in the range of ATT 400-800/DEFF 800-1600

**Comment by frankmorgner** [comment]
Thanks for the feedback!

I've quickly added Legionnaires and rerun the test with 8 Legionnaires vs 8 Legionnaires, Computer has 827 attack, 827 defense (attrition 63), my script now performed 100 fights for a player that has 0-1600 attack/defense (both raised in 10% steps). 
![grafik](https://user-images.githubusercontent.com/1266577/121265797-ac4a7d80-c8b9-11eb-8d42-55cea856f3e9.png)
I'll try to check whether the hot squares are matching the ranges where the damage changes, but right now I need some sleep ,-)

**Comment by frankmorgner** [comment]
Yep, looks like the edges of the squares are marking a new value for minimum/maximum damage. So at least the simple case looks OK.

**Comment by frankmorgner** [comment]
thank you!
