### ISSUE TITLE
Feature request: settlements 

### ISSUE THREAD

**Issue by thethinker990** [mainIine/foe-helfer-extension#1883]
1. A calculation of the required goods and the amount of time would be nice, so I know if it is possible to go in gold/silver/bronze. Maybe with and without the x4-bonus percentage. E. g. 24 hours left, need of 30 goods and possibility of the gold-price. 

2. Include of the lowest diplomaty items and alternative calculations. or maybe even the option. E.g.: vikings 50 diplomacy needed
 - 3x shrine
 - 2x shrine, 1x runestone
 - 1x shrine, 5x runestone
 - 9x runestone

**Comment by andrgin** [comment]
1.) This is a bit more complicated because (especially for Egypt) collecting all goods does not finish all quests. This only gets you unlock the last building which enables you to unlock the 2nd last quest.
There is still a last quest of collect goods of each type and a certain amount of settlement currency. You have to add time for that as well (building the missing buildings, collecting the resources, for egypt maybe collect some missing loot etc.)

Also it is hard to tell how long you will have to wait because 4x bonus is random and you also get random goods for Japan/Aztecs. You could take a "worst case" approach, but this may be completely off if you are still missing a lot of goods. You may take an "average" approach, but this may also be off by quite a lot if there are only a few goods missing. Lets say you are missing 11 goods and do a 8h productions while having a 25% chance. The average production would be 17.5 goods in 8 hours, but the chance of getting the 11 goods is still only 25%.
Next problem is that the tools does not know which production options you want to do. Maybe you log in only once a day and the 4h and 8h are not an option for you. Maybe you can do 4x4h and 1x8h (in the night), maybe it is 2x8h and 1x4h (missing 4h once).

2.) My plan was to adapt it that only decorations are shown, but not cultural buildings like shrine/market etc. because those need population as well so total efficiency is much lower showing always the most efficient one.

**Comment by thethinker990** [comment]
1.) You must not create a quite complicated formula. You can add 8h at the end, hard coded. I meant more like:
e.g. Vikings: You got 16d (384h) for the first run. You need 938 goods to finish the settlement. So the formula for one building is: 

With 4h production you could do 960 goods in 384h* and 28,8 goods**
With 8h production you could do 960 goods in 384h* and 28,8 goods**
With 24h production you could do 320 goods in 320h* and 9,6 goods**
*without any four-times-bonus
**estimated additional with bonus

So we see, at the first run it's enough to build only one production building and run with 8h to finish the settlement (without paying attention to the need of different goods).

Probably at some point you have not to do anymore the 8h production, but you could do the 24h production to be in time. This would be nice to know.

One could set the raw data he want's to play with in the settings tab (e.g.: "I play with 8h production and got X production buildings atm"

Maybe this could be implemented somehow.

2.) Yeah, that would be nice. The most time I build only the decorations, because e.g. 2x totems are more efficient than 1x shrine.

Off-Topic: Do you got anywhere a tutorial/forum/anything how to read the raw data from the game from the sqlite-files? I don't get it and can't find the location in the code.
