### ISSUE TITLE
Problem of calculation on GB Investments window

### ISSUE THREAD

**Issue by IngenieurMeca** [mainIine/foe-helfer-extension#1884]
Hello,
There is a problem of synchronisation with the GB investments window.
It always stays at "0".
I'm on Firefox navigator.
Can you help me please or correct the bug 😊
Thanks for your response 

![Investments](https://user-images.githubusercontent.com/79056153/109637609-4bd6d200-7b4d-11eb-8d87-40254f8177ff.JPG)

**Comment by danielvoigt01** [comment]
Hi, which version of FoE Helper are you currently using? You can see it in FoE Helper Settings -> Version.

**Comment by IngenieurMeca** [comment]
version 2.5.6.2

**Comment by danielvoigt01** [comment]
Did you get an error in the Firefox error console (press F12 -> Tab "Console")

**Comment by IngenieurMeca** [comment]
Yes, I do.
![erreur GB investments](https://user-images.githubusercontent.com/79056153/109671196-29a47a80-7b74-11eb-8d43-1b08e2a23cf7.JPG)

**Comment by IngenieurMeca** [comment]
![erreur 2 GB investments](https://user-images.githubusercontent.com/79056153/109672491-62911f00-7b75-11eb-93cd-1b57f0a4227c.JPG)

**Comment by danielvoigt01** [comment]
I saw that you allready had the problem before the last (2.5.6.2) update? #1856 

As far as I can tell up to now there is something wrong with your local web storage, because we have no similiar known issue. 
If you haven't tried this yet, delete the extension and install it again. 

You can also try to delete the local storage DB but in this case you LOST all your statistic data!

If you are on site forgeofempires:
Press F12 go to Tab (Web)-Storage, find IndexDB -> forgeofempires.com -> FoeHelperDB_[NUMBER] 
Right click and press Delete FoeHelperDB_[NUMBER].
The extension automatically creates a new empty DB after reload.
![Auswahl_009](https://user-images.githubusercontent.com/46729881/109682067-5e1d3400-7b7e-11eb-892c-30888e026557.jpg)

**Comment by andrgin** [comment]
The import error message is:
InvalidStateError: A mutation operaton was attempted on a database that did not allow mutations

This happens when the privacy settings of Firefox prevent permanently storing data. While most other settings simply get lost after closing the browser all IndexDB based tools as FP Investments, Statistics, Moppelhelper etc. do not work at all.

You should try the following:
.) Do not access the game in private mode
.) Options => privacy and security => Delete cookies and site data when Firefox is closed must be DISABLED
.) Options => privacy and security => History => Set to "remember history"
