### ISSUE TITLE
Bug: Negotiation mistake, one have to click ok

### ISSUE THREAD

**Issue by thethinker990** [mainIine/foe-helfer-extension#1890]
If one make a mistake while negotiation one have to click "Ok" to get back the next guesses. It would be nice if this behaviour wouldn't be. Probably it's not a bug, but a feature.

**Comment by andrgin** [comment]
It is important to show the player that he did something wrong and because of that the negotiation helper can not continue and will just show you which goods are left.
If players mistype one hotkey and still press space it this means they have not noticed that something went wrong and need to get informed. Otherwise we would get flooded by "why do the suggestions not continue".

**Comment by thethinker990** [comment]
So it is actually a Feature. 
Maybe you could add a option to continue on error/warning. Sometimes I use a different good on purpose and have to touch my mouse, which consumes a lot of time.

**Comment by andrgin** [comment]
All the negotiation tables are precalculated as the calculation overhead would be far too high (up to 16 hours with a 9900K using 16 threads). It is not possible to just continue as long as it cant be solved by just reordering of unused goods. If you did not follow the suggested path there are no more suggestions. All we can do is showing which goods are still possible for each place.

**Comment by thethinker990** [comment]
> All we can do is showing which goods are still possible for each place.
This is what I meant. A option to activate this.
