### ISSUE TITLE
"<" in Title; Infobox

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#1941]
If the title of a thread contains the "<" character, the Infobox incorrectly shows the entry for those messages in that thread. We have a thread called "Obs/Atom(<lvl60) 2️⃣.0️⃣ APRIL SALE!", but in the Infobox, it seems the entry is incorrectly formatted:

![image](https://user-images.githubusercontent.com/9089026/113519444-7ffa4400-958c-11eb-8075-73a11ddc2c6c.png)

There might be other characters (I assume) that triggers this.

**Browser:** Chrome
**Version:** 2.5.6.3

**Comment by mainIine** [comment]
It looks like the browser is trying to parse this as an HTML tag. We will change that.

**Comment by mainIine** [comment]
I think i got it.

![Bildschirmfoto 2021-04-08 um 12 31 04](https://user-images.githubusercontent.com/834814/114012254-63992880-9866-11eb-82eb-9e88fc0dd968.png)

**Comment by Arklur** [comment]
Hm...interesting. Usually it works, but "after some time", it breaks?
![image](https://user-images.githubusercontent.com/9089026/116286144-2b16ab80-a78f-11eb-95d7-9af5d9389cb5.png)

**Comment by frank42hh** [comment]
Because this report has been mentioned in a discord chat, I'm adding my screenshot here for reference.

![Screenshot 2021-05-21 181234](https://user-images.githubusercontent.com/17932878/119259301-e3d4dc80-bbcd-11eb-932c-0dc3f6d3693f.png)

It seems that for some reason "amp;" gets added and added and added until some overflow happens and it starts again with every new message.
