### ISSUE TITLE
Firefox problem - 2.5.7.0

### ISSUE THREAD

**Issue by ecthelioni** [mainIine/foe-helfer-extension#1964]
I had installed old version FoE helper and Firefox dont automaticly update to version 2.5.7.0
I try unistalll old version and install new version 2.5.7.0 
New version cannot be installed from firefox addd-on store , i see this error:
![image](https://user-images.githubusercontent.com/60727513/115180904-fd6a9c00-a0d6-11eb-9f8a-bb42803ff908.png)

**Comment by ecthelioni** [comment]
Scrrenshot of error in englsih is here:
[https://ctrlv.cz/5gNX](url)

**Comment by RobbertBakker83** [comment]
I see my add-on hasn't updated either. Also in firefox. I have an issue with the GB investment window for you own GB not showing correctly for the Floating Island GB. It just shows a small slider bar type image. When I open another GB it will show as it should. But then switching back tot FI it stays on the old GB. 

That's probably due to missing the updated version? Or is it a seperate issue?

![afbeelding](https://user-images.githubusercontent.com/82800072/115194350-a3290580-a0ed-11eb-8e92-3e64ee9dd543.png)

**Comment by enricomg** [comment]
I tried to upload it manually, it gives me an error, because a file is damaged

**Comment by Gindi4711** [comment]
1.) There seems to be a problem with the Firefox installer. We have uploaded it again, but it may take a few hours until it is unlocked by Mozilla. In the meantime do not remove the old version 2.5.6.3.

2.) The bug with the flying island is fixed in 2.5.7.0

**Comment by RobbertBakker83** [comment]
That did it for me! I forced the check for updates on my addons and it went through smoothly. I have the Island helper! TNX!
