### ISSUE TITLE
Is Foe Helper illegal or not?

### ISSUE THREAD

**Issue by Judassimo** [mainIine/foe-helfer-extension#2096]
I am playing FOE in Turkish server. I have added Foe-Helper extension into my browser and deeply enjoyed its useful features. On the other hand, last night I was banned for 2 hours by the administration for the reason of "using illegal bot-script etc". I contacted with them and stated that I only use Foe-Helper which I don't think it has any illegal features at all. Nevertheless, they insisted that the Foe Helper is an illegal software and if I use again, I will be punished harder. So what's going on? Foe Helper is illegal or not? Please enlighten us about this matter. 
I thank you already.

**Comment by SkateScout** [comment]
Did you use only foe helper? Can you post an screenshot of installed plugins?

**Comment by outoftheline** [comment]
Please have a look at your installed extensions and look for 
- foe power tools
- foe smart scripts

Those are illegal, because they use automation.

FoE Helper is still tolerated by InnoGames. Support is not really helpful in that matter, because regular supporters have no clue about this kind of stuff.

**Comment by Judassimo** [comment]
System operator's reply message that is sent to me is attached. Let me translate it for you:
![Sysop's Message](https://user-images.githubusercontent.com/87488308/125853843-740a09b0-2164-4f02-ae2f-24cab661bac3.png)

Hello Judassimo,
Dear Gamer,
First of all, I like to inform you that all illegal softwares and browser extensions are detected by our bots and the punishment procedure is automatically implemented. Furthermore, any extensions you use, such as Foe Helper etc., are classified as "illegal". Let me remind you that if we detect any further use of such softwares, you will be punished harder. Healty days...
Respects,
beyazgiyenadam
Super Game Operator

**Comment by SkateScout** [comment]
We do not need the information what you received but what plugins are installed. The hint is that you installed more than only foe-helper

**Comment by Judassimo** [comment]
I think, You're missing the point. Operator have evidently mentioned that "Foe Helper" as an illegal extension. That's the point and no matter what did I use with my Browser.

**Comment by Gindi4711** [comment]
This is a wrong information by the support guy. Afaik the official statement from Inno is:
.) All tools that violate the game rules are not allowed
.) The player is responsible if the extension violates the game rules or not
.) Inno cannot give information to the user which tools violate game rules and which do not

Foe helper does not violate game rules. About 1 year ago Inno checked Foe helper and requested some features to be changed or removed, which we did. Since then we did not add any new features that we think to be a possible violation of game rules.

Also Foe helper currently has over 100K installations. So far all reports of banned users we have investigated are because the player had another forbidden tool installed. The most common ones are "Foe Powertools" and "foe smart scripts".

.) Inno detects if you have an illegal extension installed. It does not matter if you use it or not.
.) Bans by Inno are not sent out immediately. Sometimes they wait some time and send out bans later.

**Comment by Judassimo** [comment]
So you're saying the operator must be wrong and Foe Helper is not illegal. I like to use Foe Helper and I don't have any intention to give it up. I will continue to use it as a browser extension. Through any future actions to be made by the operators, (e.g. tolerating or rebanning), we definitly learn is Foe Helper illegal or not in the Inno Game's eyes.
Thank you very much for your attentions and helps.

**Comment by Gindi4711** [comment]
If Inno detects the use of an illegal tool, bans are given to ALL players using that tool. So as long as you are the only one here you know it is not foe helper ;-)

Normally bans are: 2 hours for 1st offense, 24 hours for second offense and 3rd offense will be permanent.
So in your case I would start searching for illegal extensions on all of your PCs and and all browsers.

**Comment by Melkor73** [comment]
Hello,

i have the same issue, and yes i have no other extensions or scripts installed. The only thin is, that i use PC and Mobile. On Mobile Phone i am using the Android Beta-App for FOE on the Liveservers too. So now i got a second Ban 24 hours. My Question to the Threadowner is, are you using Beta-App for Liveserver too? This is the only thing that can explain the illegal Software detection if not FOE-Helper itself is detected.
