### ISSUE TITLE
New update in GB calculator is not good.

### ISSUE THREAD

**Issue by belikoviv** [mainIine/foe-helfer-extension#2098]
> Places that do not yield FP as a patron reward are suggested with 1FP.

It is very uncomfortable!

Good mode - to allow me set my own value of investment for places without FP reward (different values for different GBs).

Normal mode - leave it as was before update (zero FP count).

And hardcoded 1 FP - is very bad :(

**Comment by Gindi4711** [comment]
I dont see a situation where 1FP would be an issue:
.) If you do not want to give away a place simply do not select P5 in the copy box.
.) If you are using Auto place select without checking the copy box it should never include P5(1FP) because it is not safe.
.) When using the All option when powerleveling: Who ares if P5(1FP) is included if there is not guy doing P5 anyway.

But I think I will add an option to disable the 1FP and switch back to 0FP.

For using individual different FP values for different great buildings:
I think this would make things too complicated. What if you select 20FP (because you well 4 BP for 5FP each) and P5 gives 10FP instead of 0?

**Comment by belikoviv** [comment]
> For using individual different FP values for different great buildings:
> I think this would make things too complicated.

No. It's simple.
0 FP by default in all levels of all GBs.
And input field (instead of %%) where I may set non-zero value for current level of current GB.

**Comment by JhonnyBn** [comment]
I was about to suggest this... so adding to this discussion:

In GB Calculator box, add option to show 0 FP if there is no FP reward
![image](https://user-images.githubusercontent.com/29382833/126851556-92810559-3835-4200-a044-380429e4b86e.png)
If option active, places with no FP reward show 0 FP and owner to add must pay these FPs

This option could be in settings box or in the little gear icon in the GB box
![image](https://user-images.githubusercontent.com/29382833/126851836-3fbbb0d1-ef41-4043-b29a-b082acc3e6e7.png)

![image](https://user-images.githubusercontent.com/29382833/126851804-27982d43-ac41-46c5-9fe9-81d810fc2f63.png)

**Comment by JhonnyBn** [comment]
> But I think I will add an option to disable the 1FP and switch back to 0FP.

Me and my friends like to power-level using the normal calculator, seeing the numbers level-by-level. So it would be really cool to add this option, because if there is no 5th place, every level whoever pays for the owner needs to remember to sum +1, and this slows down the leveling.
