### ISSUE TITLE
Idea - GBG; Neg; Show numbers for goods

### ISSUE THREAD

**Issue by Arklur** [mainIine/foe-helfer-extension#2107]
Would it be against the "rules" if the number for the goods would show in a separate panel? Currently, it's not really possible to use hotkeys because I (would) need to remember the numbers for each good, so using mouse is much more easy.

I was thinking of something like this (although, obviously using your current design):

When opening the neg panel:
![image](https://user-images.githubusercontent.com/9089026/126745857-7ee132ee-dfb1-4868-8784-31989584bf74.png)

After the first "round":
![image](https://user-images.githubusercontent.com/9089026/126745962-dbf408eb-a354-43fc-a0f0-252889a19c38.png)

**Comment by Gindi4711** [comment]
I dont know if Inno would treat this as a violation, but I would expect quite some trouble trying to hit the existing icons.

Also we want to avoid integrating helper content into Inno content if possible because this would make it hard for players to identify which content is produced by us and which is produced by Inno. We do not want helper users to contact Inno if there is a bug with our content, because if that happens very often supporters may get annoyed and that will backfire some time in the future.

**Comment by Arklur** [comment]
I see what you mean by placing the numbers as seen on the 2nd image, but...what about the one that is only showing the numbers for the goods, what I put on the left side? That would be the big deal, the numbers wouldn't make that much of a difference, but thought they might be a QoL addition, seeing the numbers there, no need to watch left-and-right to get the goods/numbers correct.
