### ISSUE TITLE
Uncaught Reference Error

### ISSUE THREAD

**Issue by That1SouthernGuy** [mainIine/foe-helfer-extension#2130]
Here is a error I am getting on the beta version of FOE Helper.  The version is 2.5.9.1, Here is the details listed in the error.. 

Errors
Uncaught ReferenceError: StrategyPoints is not defined
Context
https://us11.forgeofempires.com/game/index?
Stack Trace

ResizeFunctions: () => {

		// FP-Bar
		StrategyPoints.HandleWindowResize();
	},

**Comment by Gindi4711** [comment]
It is working fine for me. Also there have not been any changes to strategypoints.js since the last update, so I suppose it is a system specific issue.

.) Can you check unter chrome://extensions if you have more than 1 instance of Foe helper active.
.) Try reloading the extension
.) If that does not help download a fresh copy from beta branch and this as an extension (make sure to deactivate the old one first)

If this does not fix your problem:
.) Do you get this error message when loading the game or during gameplay?
.) If you resize your window does not error appear again?
.) If the error message appears only while loading the game do you have any other extensions that could trigger a window resize when reloading the game.

**Comment by That1SouthernGuy** [comment]
1.I have tried uninstalling FOE HELPER Beta and reinstalling the fresh code from here and still get the same error.
2. I have tried reloading the extension as well and that did not work. 
3.  I have tried a fresh copy and that does not work still get the same error.

1. The error is in the extension  interface where you see your extension. It list the error on the extension itself. 
2. It does it no matter what size the window is.
3. As stated the error is where you see your extensions listed. it shows the error on the extension itself.

I am using Brave Version 1.28.106 Chromium: 92.0.4515.159 (Official Build) (64-bit)
