### ISSUE TITLE
Blue Galaxy Helper

### ISSUE THREAD

**Issue by LordFelix** [mainIine/foe-helfer-extension#2139]
I'm aware of the "Do not suggest" of guaranteed diamond collections. This is different.

Request adding (either at the top or bottom), on the Blue Galaxy Helper window, the list of the buildings (no more than BG charges) that **MIGHT** give diamonds to the player, so they can choose to gamble ignoring BG suggestions to try to double diamonds, regardless of them actually having diamonds to collect or not.
If implemented, request it be enabled/disabled by checkbox.

Example with a lvl 1 BG in a crappy city:

Shinto Temple
Mikawa Bridge
Art Exhibition
World's Fair
---------------
Crow's Nest
Wishing Well

**Comment by Gindi4711** [comment]
My long term plan is to switch at least blue galaxy helper and building efficiency from from "current production" to "average production" where I can include the average diamond production as well (because it is not using hidden information any more) because there are more and more cases where current production is problematic (for example the pirate hideout exploit to choose your production or building efficiency changing a lot depending on random production).

Unfortunately this is quite complicated and I have not found a solution to some cases yet. For example I have not found a way to calculate FP of chain buildings yet without checking the whole chain logic.

**Comment by SkateScout** [comment]
Hi, the Chain Logic is not so complicated. And the hideout exploit is already been disabled.

**Comment by outoftheline** [comment]
We will not build this, we'll rather gocus on the fragments now
