### ISSUE TITLE
Copy the calculator for friends

### ISSUE THREAD

**Issue by Mixjager** [mainIine/foe-helfer-extension#2152]
Hi there
first thank you all for the amazing job, the assistant is so great and helpufull in game !!
As I like to help other players, it appears that a lot of them don't have any calculator to lvl their GB, spend too many FP, get usually snipe. So quite often I open the calculator and write them the different steps of FP to invest to get places secure.
Would it be possible to add a copy button to link directly all this informations to someone ?
I think it could gain some time, happyness and pleasure to play together for some people 
Thank you again :)

**Comment by Gindi4711** [comment]
GB Calculator works with GBs of other players as well.
There is an option in the settings menu if you want it enabled for other players as well.

**Comment by Mixjager** [comment]
Yes and as I know this is a new option (or may be I didn't saw it before) 
what I'm trying to ask is to copy all PF a friend have to put for a new lvl, because as I know the copy button apear only when places are safe/secure or I would like it to be possible to link what I can see for is GB on my calculator.
Hope to be more clear

**Comment by coderwolf2015** [comment]
I think this is referring to an ability to copy the main (and safe) points in the calculation to assist other players(external to the player who actually is using FOE Helper).  This would have to be text based to allow for copy into a message.  It is more of a lock calculator.
Though I do the same on occasion, The problem I see with this is the calculations are so dynamic that if a contributor places too much or too little it would change the values needed for proper re-allocation of the spots.  It is best for the other player to use Foe Helper themselves.  If the other player is using a phone and does not have access to use the browser addon there are also web based tools that can do the equivalent.  I think it would be more effective(though the other tools can not act as quickly(because all the values must be manually entered)) to teach these tools.

**Comment by Mixjager** [comment]
Thanks @coderwolf2015 you understand excatly my demand and I get your answer too
As the calculator tell me how to adjust when a or some layers put PF, I thought it would be possible. 
Moreover, that being possible would allow to link by a simple clik, wich I can easily do a lot each day as it is very quick
I get what you say that there are others solutions and if those lazy players don't use them it's their problem but I don't like to see mates being snipes and loosing so many time

Again thx everyone here for the amazing work on the tool
