### ISSUE TITLE
beta - windows do not move off screen. 

### ISSUE THREAD

**Issue by IgorKaisa594** [mainIine/foe-helfer-extension#2408]
bug or feature?

**Comment by Parama91** [comment]
Feature, because we had many user who were searching for their boxes 😂

**Comment by Cady36** [comment]
lol, I'd make it an option not a fixed feature. Sometimes it's nice to be able to temporarily move stuff out of the way, especially with the big windows.

**Comment by Parama91** [comment]
Well.. if we make an option for every little change we make, you have 99% of the extension settings and only 1% function. We are currently refactoring the settings itself and move box related settings to the boxes itself which makes it easier to expand the box settings. After that we are more flexible on which and what we represent as settings.

**Comment by Cady36** [comment]
Oh, I do get it, and I'll live with it. It makes it less efficient for me, because of the need to open and close boxes all the time. Especially with the bigger boxes, you need to move them partly out of the way sometimes for just a sec. (Think FOE Market + Market Filter, as an example.) It feels like (for me only/my playstyle) that because some people aren't paying attention to the _tools already provided_ to reset their box positions when they lose something, I'm losing functionality.

**Comment by Cady36** [comment]
That sounds a bit programmatically complex for an issue this small, I think, and wouldn't completely solve the problem. e.g. for that Market example, I move it aside (slightly off the screen on the edge) to get to the market screen, then move it back.

I'll get used to it as is. :)

I did just figure out if I change the font-size on that table, I can fit everything on screen at once after sizing the table down, and it doesn't need to be moved, then. I could probably handle similar issues the same way. May drag out StyleBot. lol.

**Comment by Parama91** [comment]
Hm true, if you release the box it pops back in and it hides the market again

**Comment by Beelzebob6666** [comment]
you know that most (if not all) of the bigger windows have a minimize button?

**Comment by Cady36** [comment]
In the Market example, I'm looking at the filter and then going to places in the market, getting info from the filter, opening something in the market. Does that make more sense? I'm reading the data on the Helper page on the right and using that information to work in the Market. 

Be that as it may, I can adjust the font-size of that window so that the Filter box fits between the Market popup and the edge of the screen, and all of the text is readable. So that ought to work for me.

**Comment by Beelzebob6666** [comment]
boxes are now allowed to move out the window to a certain degree

**Comment by SkateScout** [comment]
@Beelzebob6666 can you give an link where i can find any information how boxes can be moved out of the window ?

**Comment by Beelzebob6666** [comment]
sorry for the misconception - boxes will not move out of of the window - they will just be allowed to be partially "off-screen"
