### ISSUE TITLE
Invested FPs

### ISSUE THREAD

**Issue by Veru9** [mainIine/foe-helfer-extension#2425]
Hi, I have to hide my own buidlings every day in the investment summary, why? I keep hiding it, yet it always comes back out. Is it a bug or just something you don't know how to control? It's very annoying because it messses up the number of forge points I have in total. Why does it keep on appearing? Or maybe why there are my buildings listed at all when it's really not even an investment if it's my own GB?

**Comment by Parama91** [comment]
Your own buildings only appear in the list when you put FPs in it, if you update the list by going to your townhall and investments (or how its called), then your buildings are hidden again ;)

**Comment by Veru9** [comment]
Well, it's very annoying. If I hide it, I expect it to be hidden.

**Comment by Beelzebob6666** [comment]
I assume you mean this window:
![image](https://user-images.githubusercontent.com/66054355/164295151-6babe777-91a5-4e8b-bd2d-d3a71dc8da87.png)
yeah, this window should not show your own investments
I could imagine that the data is somehow faulty because your own GB somehow ended up in the local database for the investments.
maybe @mainIine can explain to you how to reset the data manually

**Comment by Beelzebob6666** [comment]
the own GB are added to the list only when you open your own LB list (from the social bar for example)
Your own GB should get cleared from the list when you open the GB list from the town hall.
So best option is to just remove the button for the window from the menu and in the settings activate for the investment box to open when you open the GB list in the town hall
