### ISSUE TITLE
Show Player links option affects Sets & Upgrades behavior

### ISSUE THREAD

**Issue by exxaminer** [mainIine/foe-helfer-extension#2493]
Hi, when I turn off the option Show Player links, it also removes links from Sets, Upgrades & Kits. IMHO something completely different

Windows 10 / Chrome 103.0.5060.134 (Official Build) (64-bit)
Version 2.9.3.0 
Player ID: 851874897
Guild ID: 1042
World: en18

Player links active:
![image](https://user-images.githubusercontent.com/48965178/182182116-5ca5ef3b-0d66-4c0d-9979-3fec9dfd94df.png)

Player links inactive:
![image](https://user-images.githubusercontent.com/48965178/182182176-97b4a83b-8f2c-4a90-99da-a1edce3209c1.png)

**Comment by oesi03** [comment]
Vollkommen korrekt dass das so funktioniert und so gewollt.
Da es ein globaler Schalter für alle Links werden soll.
Habe nur noch nicht die Texte des Player-Links angepasst, da auch noch Gilden-Links (GEX Ergebnisse) hinzu kommen sollen!


It's absolutely correct that it works that way and that's how it's intended.
Because it should become a global switch for all links.
I just haven't adjusted the texts of the player links yet, because there are also guild links (GE Results) to be added!
