### ISSUE TITLE
Prevention box - Costcalculator

### ISSUE THREAD

**Issue by mainIine** [mainIine/foe-helfer-extension#2508]
Some users asked for a module:
Prevention box on the input field of foreign LGs to not accidentally pay in forge points again.
This option should be disabled by default.

**Comment by Beelzebob6666** [comment]
not sure we can do anything here - because the only way that we could implement this was to listen for the "FP contributed" json - when the primary error here is that that json is not sent/received properly in the cases of double contributions (I think that is highly likely) then our code also would not display the prevention box anyway...

**Comment by Beelzebob6666** [comment]
I believe it is implemented - not sure thought if it indeed works as intended in the buggy cases for which the feature is sought in the first place. I never had that occuring to me...
