### ISSUE TITLE
Peculiar calculcation error on LG-Calc

### ISSUE THREAD

**Issue by Soulprayer79** [mainIine/foe-helfer-extension#2514]
Hello,
in the current version 2.11.0.0. of the Helper, I just get the following strange display in the CdM.
P1 is not even overpaid, but underpaid 708 instead of 713.
I would have expected P2 to be 361, P3 124 etc in it.

The funny thing is that it's currently the only LG that doesn't calculate the co-payments correctly.
![image](https://user-images.githubusercontent.com/82806099/188392066-520c2ebf-6886-468f-8181-7b0947fa4e4f.png)

**Comment by Beelzebob6666** [comment]
the calculations seem correct - exactly because current P1 is underpayed, someone else still could take P1 for 713 - current P1 would go down to P2 and it would be a massive overpayment

if you want the current P2 to get the place even though it is underpayer, you have to add his current bid in the "Ext" column

**Comment by Soulprayer79** [comment]
> if you want the current P2 to get the place even though it is underpayer, you have to add his current bid in the "Ext" column
Ah! That makes sense, thanks for explaining!
