### ISSUE TITLE
Improvement GB Calculator

### ISSUE THREAD

**Issue by enriqueglopez** [mainIine/foe-helfer-extension#2546]
Would be nice if you can sort the positions in this window:

![image](https://user-images.githubusercontent.com/61711086/204921395-333106b5-b94b-4c10-a16a-9099aab5c83a.png)

By defualt, is copied like: GB 10->11 P5, P4, P3, P2, P1

If you could sort the values like GB 10->11 P1 P2 P3 P4 P5 this would be perfect.

I don't know if you actually can. If its possible please tell me

**Comment by Gindi4711** [comment]
Power leveling uses the same copy format as GB Calculator.
You can edit with via the arrow (see screenshot).
You can change the order of spots by deslecting the "descending" option.

Descending is the default value for sorting because it is easier to delete the spot when posted in 1.9 groups especially on mobile

**Comment by Gindi4711** [comment]
<img width="395" alt="Screen" src="https://user-images.githubusercontent.com/55417498/205167460-b9901080-7e93-48b3-9f9f-2c48a2d423ae.png">

**Comment by enriqueglopez** [comment]
Omg thanks! Didn't know!
