### ISSUE TITLE
GbG window problem

### ISSUE THREAD

**Issue by zoharsivan** [mainIine/foe-helfer-extension#2559]
Hi all,
I'm suddenly unable to set alerts in the FOE helper GbG window.
The version I'm using is 3.001.

Any help will be appreciated,
Zohar

**Comment by outoftheline** [comment]
I looked into it for a minute, might be a change in the game itself that prevents the notifications from saving.

**Comment by BDAHLL** [comment]
I have been having this issue for almost a month now.  Happens on two different PC's so is not localized to a bad PC.  I used this GBG alerts feature extensively when it used to work to set up Windows alerts for upcoming tiles that were opening for battle.  Since this bug cropped up, you can set the alerts but they disappear totally in about 60 seconds when you try to view them on the Alerts Notification icon.  The GBG (guild battleground) icon still shows the alerts as active but they do not trigger the windows pop up notification anymore....    FOE PC version info:  1.247.38dae1621d (04.01.2023 08:34)    FOE Helper:  Version
3.0.0.1

**Comment by kettyo** [comment]
Any progress on this issue? Not only GBG alerts are disfunctional but all alerts generally. It's a major function of the helper so please look into this. Thanks a lot!

**Comment by BDAHLL** [comment]
Can we get an update on this issue for getting this looked at and fixed? This is probably my most used feature of the FOE Helper and is truly missed. GBG alerts for when tiles open up are critical when racing other guilds to the tile ownerships....

**Comment by kettyo** [comment]
The problem might be related to the new game feature of browser notifications. It might conflict with the helper's way of saving it's own alerts.

**Comment by outoftheline** [comment]
will close this, continuing here -> #2563
