### ISSUE TITLE
Guild Member Overview: the data of Great Buildings are not up to date

### ISSUE THREAD

**Issue by NicolaP8** [mainIine/foe-helfer-extension#2737]
I tried to open the Guild member list, the GBs of some player but the data doesn't refresh and remains old and not accurate.
Last version (3.5.0.0) on Firefox.

Edit: of course after posting this I found some relevant information.
Suggestion: add the informations to update the data in the settings panel!

**Comment by AlfonZ42** [comment]
Where exactly in *Settings* would you expect the information of "visit all guildmate's town to update the data in *Guild Member Overview*" to be?  
Because, currently, the only Guild-related setting there is *Guild Treasury Export Log tool*. And I would not expect such information to be found with it.  

Would making the notification of "Visit your members towns to update the building statistic." (present in *Great Buildings*, *Guild Buildings*, and *Treasury Goods* tabs) more visible be helpful for you?

**Comment by NicolaP8** [comment]
The Guild Member Overview window has a small settings icon on top right where you can set some properties and export the data. 
Maybe this is the best place for a help button or e small message (with a link to the long explanation in your site).

**Comment by outoftheline** [comment]
there already is a ? button on some windows, but hardly anyone clicks them and the info is mostly outdated, because we do not have anyone who is willing to write guides.

**Comment by Dima-33** [comment]
Hi, 
Guild data not updating, latest version of chrome shows last update back in may of 23

**Comment by outoftheline** [comment]
> Hi, Guild data not updating, latest version of chrome shows last update back in may of 23

Did you visit their cities?

**Comment by Dima-33** [comment]
Hi Yes they not even in my guild

**Comment by outoftheline** [comment]
Sorry, what?

**Comment by Dima-33** [comment]
Hi. what I see is that the data is not updating its stuck back on info from may of last year.  Some people no longer in my guild.

**Comment by AlfonZ42** [comment]
To get updated data for the _Guild member overview_ window, you have to do the actions that fetches them from the server:

- Open the guild window.
- Switch to the guild treasury tab.
- Visit all members' towns.
- Open the GE ranking (for members' GE performance data).
- Open the GBG ranking (for members' GBG performance data).
- Read all conversations in the message center (for members' number of messages data).
