### ISSUE TITLE
FoE Helper not getting updates since v3.5 in Edge

### ISSUE THREAD

**Issue by Coumbayah** [mainIine/foe-helfer-extension#2832]
Can't find the FoE Helper extension in the Microsoft Store either...

**Comment by outoftheline** [comment]
foe helper is no longer available through the microsoft store, because of the negotiation helper. we have a zip-file in there to look up all possible ways to negotiate. afaik microsoft does not allow extensions to have zip-files anymore.
you can still install foe helper through the chrome store, though.
