### ISSUE TITLE
Same statistics are empty

### ISSUE THREAD

**Issue by ecthelioni** [mainIine/foe-helfer-extension#529]
Hello
I have problem with same statistics.
I try install plugin in to firefox and chrome and problem is same (my standart web browser is chrome).

Problems:
Statistics - Memeber 
I see members of guild, when I open details of player I see graphs, bud I dont see great buildings

Statistics - legendary buldings is empty
Statistics events - every statistics are empty
Investmens - correctly working
Guilds expeditation - correctly working

Thank you for help

**Comment by timmep90** [comment]
Hi,
did you check your foe-helper ingame settings? There are some options, which can be optionally set, in order to submit those informations to the server. (**Transmission to foe-rechner.de** & **LB data of other guild members** & **Motivation activity**)

If all of those options are checked you must visit your guild members city in order to submit their GB data to the server.
For the Event statistics you must visit your town hall and open the occurence window _(not quite sure about the english name - containing all information about motivations, attacks, leveling GBs etc.)_.

Once you have done all the actions above it should show these informations on foe-rechner.de.

**Comment by ecthelioni** [comment]
Hi,
Thank you for your information, I have everythink correctly. 
Plugin options - i have selected every options

I open another town, i see plugin info box "sending informations"

I openb town history a and see "sending informations" 

But in web pages foe-rechner.de are statisics emty. I think, that this problem dont have olny me, becouse on forum.foe-rechner.de more people writing about this problem.

**Comment by andrgin** [comment]
Yes the great buildings menu is currently not working.

**Comment by ecthelioni** [comment]
Thank you for information and "Statistics menu" corretly working? I have problem with this section too.

**Comment by ecthelioni** [comment]
Thank you for repairing .

**Comment by outoftheline** [comment]
The Feature has been removed.
