### ISSUE TITLE
Integration of Goods Value Calculator for market

### ISSUE THREAD

**Issue by BrandyThern** [mainIine/foe-helfer-extension#668]
I wrote a small program, which we could improve and integrate into the tool:

https://github.com/BrandyThern/FoE-Calculator

If you're interested in the source code send me a message.
Greetz
Brandy Thern

**Comment by Th3C0D3R** [comment]
Lol its easy decompileable 😂 why dming you if i have the source in 1 min
You forgot some resources 😉 there are not only 8 eras

**Comment by BrandyThern** [comment]
of coarse but it's a matter of time and I'm at the moment in hma so for my purposes it is enough at the moment. :-)

**Comment by andrgin** [comment]
You are calculating the value of a good by:
Value = SpaceRequirement * Resources

I dont think this does not make much sense.

I made a good cost simulation a few months ago and my approach was:
Tiles of the building
Tiles needed for residential buildings to compensate population requirement
Tiles needed for cultural buildings to compensate happiness caused by residential buildings
Tiles needed for production buildings to produce supplies
Streets needed to connect all these buildings subtracted by the happiness generated by these streets)
For refined goods substract a certain percentage from the good output to trade back lower age goods (around 20% in most ages).

The problem of this calculation is that the actual values change a lot by things like:
.) Your era
.) Do you still need happiness or are they all angry anyway
.) Do you still need residential buildings or do your GBs and event buildings provide you with enough population anyway
.) Same for refined goods
.) Supply costs are much cheaper with lighthouse and RAH.

With my current GBs and comparing good buildings from the current and previous era the result was from -8% (Contemporary -> Tomorrow) to +62% (Bronze -> Iron).
But in reality the supply/demand situation is completely different because most players dont do such calculations and still have lots of old good buildings. The realistic value from the current age to the next is more like +40% to +100%.

So after all these calculations did not help very much and I returned to make market prices based on my previous experience. I know Tomorrow needs 1.5 to be traded down, lower ages around 1.7, higher ages are fine at 1.9.

**Comment by BrandyThern** [comment]
You are right with your further calculation but I just took this aproach because the needed ressources and space requirement are fix values for every player(of coarse not the time and space for ressource production). One of my goals was to show people that the simple approach 2:1, 1:1, 1:2 as exchange values concerning the era of the good is too shortly thought. They all argue that those would be "fair" values but I wanted to demonstrate that fairness is relatively badly calculated then. 

Perhaps it would be best to add a combo box or some check boxes to add or remove those additional factors and summands. But I guess because of many factors it will always be just an approximation.

**Comment by andrgin** [comment]
Like I said even if you calculate all the factors you are still far off. Even 2:1 is closer to the true market value than a nearly perfect calculation.
Intersting thing: While in high ages the production costs only increase about 10-20% per ages these ages are very cose to 2:1 because the high ages require lots of goods of the current era and only very few of previous ones while players are running out of reno kits to get all their event buildings at the current era.

**Comment by SkateScout** [comment]
So even if you calculate all in you miss sources of goods:
- DynaTower
- Schlittenbauer
- SaatgutTresor
And many more. And secondly no one want to take out his calculator each time he place an exchange.

**Comment by BrandyThern** [comment]
That's the reason why I think that one should have an integrated tool for the market.
