### ISSUE TITLE
New Feature - Building Kits

### ISSUE THREAD

**Issue by adwsystems** [mainIine/foe-helfer-extension#716]
The new feature seems to summarize the buildings of the kits you have. It would be nice to also show which buildings you are missing. That is make the list for each kit you have at least one piece of, display completely and display any missing pieces with a 0. For example, I have 4 pieces of the Indian Set and the palace does not appear at all. It would be nice for it to appear with a 0, to help identify which piece I am missing and should be on the look out for.

**Comment by RealTracat** [comment]
Ship upgrades seem to be missing from the list

**Comment by dsiekiera** [comment]
Innos data is incomplete. Many new building sets have no identifier whether they are a set or selection kit at all.
So also the new Hamani bridge. It is a simple building for the game.

**Comment by Timee79** [comment]
Die Registerkarte "???" zeigt beim Winterdom-Kit andere Werte als die Registerkarte "Auswahl-Kits"!
![Auswahl1](https://user-images.githubusercontent.com/60137913/79109609-f77e0480-7d78-11ea-8750-b9a7703d1e48.JPG)
![Auswahl2](https://user-images.githubusercontent.com/60137913/79109616-f9e05e80-7d78-11ea-9a6c-8157220ebf25.JPG)

**Comment by flomyen** [comment]
I was about to report a missing type of kit in the Pirate hideout set, but this issue/request has been closed as completet last year. Does it mean it was fixed for the specific set signaled here, or nothing will be done adressing this kind of missing elements (because incomplete data from Inno), or should I create a new issue?
