### ISSUE TITLE
Guild treasury simplified

### ISSUE THREAD

**Issue by jgwells1** [mainIine/foe-helfer-extension#733]
Is it possible to add a guild treasury button, and adjoining screen that gives a simple readout of levels?  Would be cool if we could cut and paste for tracking during BG, to understand the costs of buildings and the impact on treasury.

**Comment by scibuff** [comment]
I guess this is similar to [#692](https://github.com/dsiekiera/foe-helfer-extension/issues/692)

**Comment by dsiekiera** [comment]
We will discuss internally how we can best implement this.
It will be a multi-faceted module.
- To do this, you first have to track what is in the guild's warehouse
- then you need a function to select the corresponding area
- that must then be output in a box

And in the end it should also look good 😊

**Comment by jgwells1** [comment]
I posted on 692 as well.  Not sure if there is a way to peek and get the cost per building in BG. I would imagine in Diamond and Platinum the prices are consistent in each ring.

**Comment by dsiekiera** [comment]
There are already lists of hard-working players on the Internet that can be used for this. All of this has to be written together in one module.

**Comment by ljettinger** [comment]
I have another idea for this module that would be AWESOME that I just logged on to create, I'm not sure if it could be part of this or if it's a different monster...
Would it be possible to also include the ability to collect the guild treasury contributions data and present it in a worthwhile/sortable/searchable manner, even just a csv. export... I understand it would have to be primed similar to the tavern/aiding and would probably require the website, so if you think it requires its own issue, I'll create one for it... just thought I'd add it here since it's got to be a logical starting place to what's being discussed... 
thanks for your time...

**Comment by cjlear** [comment]
> Would it be possible to also include the ability to collect the guild treasury contributions data and present it in a worthwhile/sortable/searchable manner, even just a csv. export... 

+1
